services:
  db:
    image: postgres:latest
    container_name: gym-tracker-db
    environment:
      POSTGRES_DB: gymTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: node:20
    container_name: gym-tracker-frontend
    working_dir: /app
    volumes:
      - ./front_end:/app
    command: bash -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"

volumes:
  postgres_data:
